/*
 * checkbox, checkboxGroup, date, dateTime, email, multiselect, password, radioGroup,
 * relatedObjectSelect, relatedObjectMultiselect
 * select, typeSelect, text, textArea, time, wysiwyg, yesNo, json
 */

const createNewAccount = {
  formID: 'Create Account',
  formCode: 'Create Account',
  formName: 'Create Account',
  formQuestions: [
    {
      attributeID: '',
      attributeName: 'Password',
      attributeDescription: '',
      attributeCode: 'password',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: '',
      inputType: 'password',
      inputDisplayType: 'visible',
      defaultValue: '',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [],
    },
    {
      attributeID: '',
      attributeName: 'Password Conformation',
      attributeDescription: '',
      attributeCode: 'passwordConformation',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: '',
      inputType: 'password',
      inputDisplayType: 'visible',
      defaultValue: '',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [],
    },
    {
      attributeID: '',
      attributeName: 'First Name',
      attributeDescription: '',
      attributeCode: 'firstName',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: '',
      inputType: 'text',
      inputDisplayType: 'visible',
      defaultValue: '',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [],
    },
    {
      attributeID: '',
      attributeName: 'Last Name',
      attributeDescription: '',
      attributeCode: 'lastName',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: '',
      inputType: 'text',
      inputDisplayType: 'visible',
      defaultValue: '',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [],
    },
    {
      attributeID: '',
      attributeName: 'Email Address',
      attributeDescription: '',
      attributeCode: 'email',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: 'visible',
      inputType: 'email',
      defaultValue: '',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [],
    },
    {
      attributeID: '',
      attributeName: 'Phone',
      attributeDescription: '',
      attributeCode: 'phone',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: 'visible',
      inputType: 'text',
      defaultValue: '',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [],
    },
    {
      attributeID: '',
      attributeName: 'Email or Phone',
      attributeDescription: '',
      attributeCode: 'emailOrPhone',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: 'visible',
      inputType: 'radioGroup',
      defaultValue: 'email',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [
        {
          attributeOptionLabel: 'Email',
          attributeOptionValue: 'email',
          sortOrder: 1,
        },
        {
          attributeOptionLabel: 'Phone',
          attributeOptionValue: 'phone',
          sortOrder: 2,
        },
      ],
    },
    {
      attributeID: '',
      attributeName: 'Select Options',
      attributeDescription: '',
      attributeCode: 'optionsToSelect',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: 'visible',
      inputType: 'multiselect',
      defaultValue: '',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [
        {
          attributeOptionLabel: 'Option 1',
          attributeOptionValue: 'opt1',
          sortOrder: 1,
        },
        {
          attributeOptionLabel: 'Option 2',
          attributeOptionValue: 'opt2',
          sortOrder: 2,
        },
      ],
    },
    {
      attributeID: '',
      attributeName: 'Accept Terms',
      attributeDescription: '',
      attributeCode: 'acceptTerms',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: '',
      inputType: 'yesNo',
      inputDisplayType: 'visible',
      defaultValue: '',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [],
    },
    {
      attributeID: '',
      attributeName: 'markup',
      attributeDescription: '',
      attributeCode: 'markup',
      attributeHint: '',
      maxFileSize: '',
      requiredFlag: '',
      sortOrder: '',
      attributeInputDisplayType: '',
      inputType: 'wysiwyg',
      inputDisplayType: 'visible',
      defaultValue: '',
      fieldType: '',
      validationRegex: '',
      validationMessage: '',
      options: [],
    },
  ],
}

const createNewAccountLayout = [
  {
    ID: '',
    label: '',
    orientation: 'Horizontal',
    sortOrder: 1,
    elements: 'firstName,lastName',
  },
  {
    ID: '',
    label: '',
    sortOrder: 2,
    orientation: 'Vertical',
    elements: 'phoneNumber,emailAddress',
  },
]

export { createNewAccount, createNewAccountLayout }
